FROM python:3.9-slim

WORKDIR /app

# --- TAMBAHAN PENTING UNTUK USB ---
# Kita perlu menginstal libusb agar PyUSB bisa bekerja
RUN apt-get update && apt-get install -y \
    libusb-1.0-0 \
    libusb-1.0-0-dev \
    && rm -rf /var/lib/apt/lists/*
# ----------------------------------

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "main.app:app", "--host", "0.0.0.0", "--port", "8000"]
